spring:
  datasource:
    url: jdbc:mysql://localhost:32768/mydatabase?useSSL=false&serverTimezone=UTC
    username: root
    password: verysecret
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      platform: mysql
